# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      JHI_E2E_HEADLESS: 'true'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 14.16.1
      - uses: actions/setup-java@v1
        with:
            java-version: '11.x'
            
        # Install node packages
      - name: Install node.js packages
        run: npm install

        # Run tests
      #- name: Run frontend test
        #run: npm run ci:frontend:test

      #- name: Run backend test
        #run: chmod +x mvnw && npm run ci:backend:test
        
      #- name: Run E2E tests
        #run: |
          #./mvnw -ntp verify -DskipTests --batch-mode "-Pprod" "-Pe2e" "-Denforcer.skip=true"*
          #npm run ci:e2e:prepare:docker
          #npm run ci:e2e:run
          #npm run ci:e2e:teardown
        
      - name: Build prod
        run: npm run webapp:build:prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
            java-version: '11.x'
      
      - name: Deploy app to Heroku
        run: ./mvnw -ntp com.heroku.sdk:heroku-maven-plugin:2.0.5:deploy -DskipTests -Pprod -Dheroku.buildpacks=heroku/jvm -Dheroku.appName=jhipster-is-so-swag
